import type {
  DataMarketListing,
  DatasetVersionQualityReport,
  MarketplaceListing,
} from "./catalog-api";

export type CatalogScene =
  | "ppe"
  | "fire"
  | "traffic"
  | "defect"
  | "parcel"
  | "shelf"
  | "forest"
  | "forest-fire"
  | "crop"
  | "orchard"
  | "apiary"
  | "road-surface"
  | "road-safety"
  | "road-slope"
  | "road-environment"
  | "tunnel"
  | "bridge"
  | "urban-illegal"
  | "urban-sanitation"
  | "urban-construction-waste"
  | "urban-site"
  | "urban-advertising"
  | "urban-municipal"
  | "urban-water"
  | "urban-ecology"
  | "urban-fire"
  | "urban-crowd"
  | "urban-traffic"
  | "urban-greening";

export type CatalogMetric = {
  label: string;
  value: string;
};

export type PreviewBox = {
  label: string;
  confidence?: string;
  x: number;
  y: number;
  width: number;
  height: number;
};

export type CatalogPreview = {
  scene: CatalogScene;
  alt: string;
  boxes: PreviewBox[];
  image_url?: string;
  aspect_ratio?: number;
};

export type AlgorithmCatalogItem = MarketplaceListing & {
  is_mock: boolean;
  preview: CatalogPreview;
  metrics: CatalogMetric[];
  classes: string[];
  model_architecture: string;
  input_size: string;
  latency_p95: string;
  evaluation_basis: string;
  updated_label: string;
};

export type DataCatalogItem = DataMarketListing & {
  is_mock: boolean;
  preview: CatalogPreview;
  scene_category: string;
  price_label: string;
  annotation_type: string;
  image_size_summary: string;
  updated_label: string;
};

const mockProvider = {
  provider_workspace_id: "mock-sensemu-verified",
  provider_name: "SenseMu 精选",
};

const algorithmDefaults = {
  deployment_id: "mock-deployment",
  capability_spec_id: "mock-capability",
  capability_version_number: 1,
  pricing_unit: "request",
  status: "published",
  published_at: "2026-08-01T08:00:00Z",
  subscription_id: null,
  subscription_status: null,
  remaining_units: null,
};

const CORE_MOCK_ALGORITHM_LISTINGS: AlgorithmCatalogItem[] = [
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-ppe",
    deployment_id: "mock-deployment-ppe",
    capability_spec_id: "mock-capability-ppe",
    capability_slug: "ppe-compliance",
    capability_display_name: "安全穿戴检测",
    capability_problem_definition: "识别作业人员是否正确佩戴安全帽与反光衣。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["固定监控视角", "白天工地", "单人或多人作业区"],
    capability_unsupported_conditions: ["人员小于画面高度 4%", "严重逆光或夜间无补光"],
    endpoint_url: "/v1/marketplace/mock-alg-ppe/infer",
    model_name: "YOLO26s",
    model_version_number: 3,
    task_type: "object-detection",
    title: "工地安全穿戴检测",
    summary: "识别人员、安全帽与反光衣，并返回未规范穿戴的位置。",
    category: "安全生产",
    price_per_1000_cents: 1680,
    monthly_quota_units: 20000,
    is_mock: true,
    preview: {
      scene: "ppe",
      alt: "工地作业人员安全穿戴检测效果样例",
      boxes: [
        { label: "人员", confidence: "0.97", x: 12, y: 8, width: 52, height: 84 },
        { label: "安全帽", confidence: "0.95", x: 22, y: 6, width: 28, height: 22 },
        { label: "反光衣", confidence: "0.93", x: 12, y: 32, width: 51, height: 43 },
      ],
    },
    metrics: [
      { label: "mAP50", value: "92.4%" },
      { label: "精确率", value: "90.8%" },
      { label: "召回率", value: "88.6%" },
    ],
    classes: ["人员", "安全帽", "未戴安全帽", "反光衣", "未穿反光衣"],
    model_architecture: "YOLO26s",
    input_size: "640 × 640",
    latency_p95: "48 ms",
    evaluation_basis: "SH17 公开数据集（8,099 张，arXiv:2407.04590）训练与验证",
    updated_label: "2026-07-28",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-fire",
    deployment_id: "mock-deployment-fire",
    capability_spec_id: "mock-capability-fire",
    capability_slug: "smoke-fire-alert",
    capability_display_name: "烟火早期识别",
    capability_problem_definition: "发现仓储与生产区域中的烟雾和明火。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["仓库固定监控", "室内厂房", "可见光画面"],
    capability_unsupported_conditions: ["蒸汽密集区域", "强光直射镜头"],
    endpoint_url: "/v1/marketplace/mock-alg-fire/infer",
    model_name: "YOLO26m",
    model_version_number: 2,
    task_type: "object-detection",
    title: "仓储烟火早期识别",
    summary: "检测烟雾与明火，适合接入仓库监控做早期风险提示。",
    category: "安全生产",
    price_per_1000_cents: 2280,
    monthly_quota_units: 15000,
    is_mock: true,
    preview: {
      scene: "fire",
      alt: "仓库烟雾与明火检测效果样例",
      boxes: [
        { label: "烟雾", confidence: "0.91", x: 29, y: 2, width: 38, height: 58 },
        { label: "明火", confidence: "0.96", x: 35, y: 47, width: 25, height: 29 },
      ],
    },
    metrics: [
      { label: "mAP50", value: "90.1%" },
      { label: "精确率", value: "91.7%" },
      { label: "召回率", value: "86.2%" },
    ],
    classes: ["烟雾", "明火"],
    model_architecture: "YOLO26m",
    input_size: "768 × 768",
    latency_p95: "72 ms",
    evaluation_basis: "D-Fire 公开数据集（21,527 张）训练与验证",
    updated_label: "2026-07-22",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-traffic",
    deployment_id: "mock-deployment-traffic",
    capability_spec_id: "mock-capability-traffic",
    capability_slug: "road-vehicle-counting",
    capability_display_name: "道路车辆统计",
    capability_problem_definition: "检测并区分道路中的常见车辆，输出逐帧数量。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["城市路口", "高位固定相机", "白天与路灯夜景"],
    capability_unsupported_conditions: ["超密集拥堵遮挡", "鱼眼畸变未校正"],
    endpoint_url: "/v1/marketplace/mock-alg-traffic/infer",
    model_name: "RT-DETR-L",
    model_version_number: 5,
    task_type: "object-detection",
    title: "道路车辆检测与计数",
    summary: "区分小客车、货车、公交车与两轮车，返回位置和数量。",
    category: "智慧交通",
    price_per_1000_cents: 1980,
    monthly_quota_units: 30000,
    is_mock: true,
    preview: {
      scene: "traffic",
      alt: "城市路口车辆检测效果样例",
      boxes: [
        { label: "货车", confidence: "0.98", x: 36, y: 34, width: 48, height: 29 },
        { label: "小客车", confidence: "0.94", x: 18, y: 62, width: 30, height: 19 },
        { label: "小客车", confidence: "0.90", x: 72, y: 60, width: 24, height: 18 },
      ],
    },
    metrics: [
      { label: "mAP50", value: "94.0%" },
      { label: "精确率", value: "92.1%" },
      { label: "召回率", value: "91.5%" },
    ],
    classes: ["小客车", "货车", "公交车", "摩托车", "自行车"],
    model_architecture: "RT-DETR-L",
    input_size: "960 × 544",
    latency_p95: "83 ms",
    evaluation_basis: "BDD100K 公开数据集（10 万张）训练与验证",
    updated_label: "2026-07-30",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-defect",
    deployment_id: "mock-deployment-defect",
    capability_spec_id: "mock-capability-defect",
    capability_slug: "metal-surface-defect",
    capability_display_name: "金属表面缺陷分割",
    capability_problem_definition: "定位金属板材表面的划痕、凹坑与氧化区域。",
    capability_output_contract: "segments.v1",
    capability_verified_scenes: ["均匀产线光源", "金属板材近景", "单件通过"],
    capability_unsupported_conditions: ["镜面强反射", "相机焦距偏离标定范围"],
    endpoint_url: "/v1/marketplace/mock-alg-defect/infer",
    model_name: "YOLO26s-seg",
    model_version_number: 4,
    task_type: "segmentation",
    title: "金属表面缺陷分割",
    summary: "定位划痕、凹坑和氧化区域，输出缺陷轮廓与面积。",
    category: "工业质检",
    price_per_1000_cents: 2880,
    monthly_quota_units: 12000,
    is_mock: true,
    preview: {
      scene: "defect",
      alt: "金属板材划痕分割效果样例",
      boxes: [{ label: "划痕", confidence: "0.89", x: 22, y: 48, width: 62, height: 17 }],
    },
    metrics: [
      { label: "mAP50", value: "88.7%" },
      { label: "精确率", value: "91.2%" },
      { label: "召回率", value: "84.9%" },
    ],
    classes: ["划痕", "凹坑", "氧化"],
    model_architecture: "YOLO26s-seg",
    input_size: "1024 × 1024",
    latency_p95: "96 ms",
    evaluation_basis: "NEU-DET / GC10-DET 公开数据集训练与验证",
    updated_label: "2026-07-19",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-parcel",
    deployment_id: "mock-deployment-parcel",
    capability_spec_id: "mock-capability-parcel",
    capability_slug: "parcel-counting",
    capability_display_name: "包裹检测与计数",
    capability_problem_definition: "检测传送带上的包裹并输出当前数量。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["俯拍传送带", "纸箱与软包", "稳定室内光照"],
    capability_unsupported_conditions: ["包裹完全重叠", "高速运动拖影"],
    endpoint_url: "/v1/marketplace/mock-alg-parcel/infer",
    model_name: "YOLO26n",
    model_version_number: 2,
    task_type: "object-detection",
    title: "快递包裹检测与计数",
    summary: "识别纸箱与软包，适合分拣线计数和漏件提示。",
    category: "仓储物流",
    price_per_1000_cents: 1380,
    monthly_quota_units: 50000,
    is_mock: true,
    preview: {
      scene: "parcel",
      alt: "物流传送带包裹检测效果样例",
      boxes: [
        { label: "纸箱", confidence: "0.96", x: 15, y: 14, width: 22, height: 18 },
        { label: "软包", confidence: "0.92", x: 34, y: 57, width: 24, height: 15 },
        { label: "纸箱", confidence: "0.98", x: 49, y: 70, width: 35, height: 25 },
      ],
    },
    metrics: [
      { label: "mAP50", value: "95.6%" },
      { label: "精确率", value: "96.0%" },
      { label: "召回率", value: "93.8%" },
    ],
    classes: ["纸箱", "软包", "编织袋"],
    model_architecture: "YOLO26n",
    input_size: "640 × 640",
    latency_p95: "34 ms",
    evaluation_basis: "演示能力卡，无公开基准；正式版本需自建测试集",
    updated_label: "2026-07-26",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-shelf",
    deployment_id: "mock-deployment-shelf",
    capability_spec_id: "mock-capability-shelf",
    capability_slug: "retail-shelf-gap",
    capability_display_name: "货架缺货识别",
    capability_problem_definition: "识别零售货架中的连续空位和低库存区域。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["正面货架图像", "便利店与商超", "标准陈列区"],
    capability_unsupported_conditions: ["玻璃柜强反光", "大面积促销牌遮挡"],
    endpoint_url: "/v1/marketplace/mock-alg-shelf/infer",
    model_name: "YOLO26s",
    model_version_number: 1,
    task_type: "object-detection",
    title: "零售货架缺货识别",
    summary: "发现连续空位和低库存区域，返回货架层级与位置。",
    category: "智慧零售",
    price_per_1000_cents: 1880,
    monthly_quota_units: 20000,
    is_mock: true,
    preview: {
      scene: "shelf",
      alt: "零售货架缺货检测效果样例",
      boxes: [{ label: "缺货区域", confidence: "0.93", x: 24, y: 24, width: 51, height: 31 }],
    },
    metrics: [
      { label: "mAP50", value: "89.5%" },
      { label: "精确率", value: "90.4%" },
      { label: "召回率", value: "87.1%" },
    ],
    classes: ["缺货区域", "低库存区域"],
    model_architecture: "YOLO26s",
    input_size: "768 × 768",
    latency_p95: "61 ms",
    evaluation_basis: "SKU-110K 公开数据集（11,762 张）训练与验证",
    updated_label: "2026-07-18",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-forest-health",
    deployment_id: "mock-deployment-forest-health",
    capability_spec_id: "mock-capability-forest-health",
    capability_slug: "forest-tree-health",
    capability_display_name: "林木健康巡检",
    capability_problem_definition: "从林区航拍或固定机位图像中发现枯死、倒伏和明显病害树木。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["林区航拍", "林道固定机位", "自然光可见光图像"],
    capability_unsupported_conditions: ["浓雾遮挡树冠", "单棵树小于画面高度 2%"],
    endpoint_url: "/v1/marketplace/mock-alg-forest-health/infer",
    model_name: "YOLO26m",
    model_version_number: 1,
    task_type: "object-detection",
    title: "林木健康巡检",
    summary: "发现枯死、倒伏与明显病害树木，适合林区巡检和复核调度。",
    category: "林业",
    price_per_1000_cents: 2480,
    monthly_quota_units: 18000,
    is_mock: true,
    preview: {
      scene: "forest",
      alt: "林区林木健康巡检效果样例",
      boxes: [
        { label: "疑似枯死树", confidence: "0.91", x: 4, y: 20, width: 18, height: 63 },
        { label: "倒伏树木", confidence: "0.88", x: 67, y: 54, width: 25, height: 18 },
      ],
    },
    metrics: [
      { label: "mAP50", value: "87.9%" },
      { label: "精确率", value: "89.1%" },
      { label: "召回率", value: "84.7%" },
    ],
    classes: ["健康树木", "疑似枯死树", "倒伏树木", "病害斑块"],
    model_architecture: "YOLO26m",
    input_size: "1280 × 720",
    latency_p95: "76 ms",
    evaluation_basis: "演示能力卡，无公开基准；正式版本需自建测试集",
    updated_label: "2026-08-02",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-forest-fire",
    deployment_id: "mock-deployment-forest-fire",
    capability_spec_id: "mock-capability-forest-fire",
    capability_slug: "forest-fire-smoke",
    capability_display_name: "森林烟火早期识别",
    capability_problem_definition: "在林区监控画面中发现早期烟雾和火点，减少人工巡屏范围。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["林区高点监控", "山地防火瞭望", "白天可见光视频"],
    capability_unsupported_conditions: ["厚云层与低云雾", "红外热成像之外的夜间画面"],
    endpoint_url: "/v1/marketplace/mock-alg-forest-fire/infer",
    model_name: "YOLO26s",
    model_version_number: 2,
    task_type: "object-detection",
    title: "森林烟火早期识别",
    summary: "识别林区早期烟雾和火点，输出告警位置与置信度。",
    category: "林业",
    price_per_1000_cents: 2980,
    monthly_quota_units: 12000,
    is_mock: true,
    preview: {
      scene: "forest-fire",
      alt: "森林烟火早期识别效果样例",
      boxes: [{ label: "烟雾", confidence: "0.93", x: 49, y: 4, width: 38, height: 30 }],
    },
    metrics: [
      { label: "mAP50", value: "91.2%" },
      { label: "精确率", value: "92.4%" },
      { label: "召回率", value: "88.9%" },
    ],
    classes: ["烟雾", "火点", "高亮反光"],
    model_architecture: "YOLO26s",
    input_size: "1280 × 720",
    latency_p95: "54 ms",
    evaluation_basis: "D-Fire / FLAME 公开数据集训练与验证",
    updated_label: "2026-08-01",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-produce-sort",
    deployment_id: "mock-deployment-produce-sort",
    capability_spec_id: "mock-capability-produce-sort",
    capability_slug: "produce-sorting",
    capability_display_name: "农产品分选识别",
    capability_problem_definition: "识别常见蔬果品类和明显外观缺陷，辅助收购与分选台抽检。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["收购分选台", "农产品近景", "室内均匀光照"],
    capability_unsupported_conditions: ["目标堆叠超过 60%", "透明塑料袋强反光"],
    endpoint_url: "/v1/marketplace/mock-alg-produce-sort/infer",
    model_name: "YOLO26s",
    model_version_number: 3,
    task_type: "object-detection",
    title: "农产品分选识别",
    summary: "识别常见蔬果品类和明显外观缺陷，适合收购、分选与质检抽查。",
    category: "农业",
    price_per_1000_cents: 1680,
    monthly_quota_units: 24000,
    is_mock: true,
    preview: {
      scene: "crop",
      alt: "农产品分选识别效果样例",
      boxes: [
        { label: "苹果", confidence: "0.96", x: 15, y: 14, width: 70, height: 70 },
      ],
    },
    metrics: [
      { label: "mAP50", value: "94.6%" },
      { label: "精确率", value: "93.8%" },
      { label: "召回率", value: "91.7%" },
    ],
    classes: ["苹果", "香蕉", "黄瓜", "胡萝卜", "辣椒", "疑似外观缺陷"],
    model_architecture: "YOLO26s",
    input_size: "512 × 512",
    latency_p95: "41 ms",
    evaluation_basis: "Fruits-360 公开数据集训练与验证",
    updated_label: "2026-07-31",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-orchard-count",
    deployment_id: "mock-deployment-orchard-count",
    capability_spec_id: "mock-capability-orchard-count",
    capability_slug: "orchard-fruit-counting",
    capability_display_name: "果园果实计数",
    capability_problem_definition: "检测果树上的果实并按区域统计数量，辅助产量预估。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["果园行间", "自然光树冠", "单果与小簇果实"],
    capability_unsupported_conditions: ["果实完全被叶片遮挡", "强风造成连续运动模糊"],
    endpoint_url: "/v1/marketplace/mock-alg-orchard-count/infer",
    model_name: "YOLO26n",
    model_version_number: 2,
    task_type: "object-detection",
    title: "果园果实计数",
    summary: "检测果实位置并按树行统计，适合采收前产量预估。",
    category: "农业",
    price_per_1000_cents: 2180,
    monthly_quota_units: 20000,
    is_mock: true,
    preview: {
      scene: "orchard",
      alt: "果园果实计数效果样例",
      boxes: [
        { label: "果实", confidence: "0.94", x: 43, y: 20, width: 12, height: 17 },
        { label: "果实", confidence: "0.91", x: 58, y: 34, width: 14, height: 18 },
        { label: "果实", confidence: "0.89", x: 22, y: 44, width: 13, height: 17 },
      ],
    },
    metrics: [
      { label: "mAP50", value: "90.8%" },
      { label: "精确率", value: "92.0%" },
      { label: "召回率", value: "87.6%" },
    ],
    classes: ["果实", "未成熟果", "病果"],
    model_architecture: "YOLO26n",
    input_size: "960 × 544",
    latency_p95: "39 ms",
    evaluation_basis: "MinneApple 公开数据集（1,349 张）训练与验证",
    updated_label: "2026-07-29",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-apiary",
    deployment_id: "mock-deployment-apiary",
    capability_spec_id: "mock-capability-apiary",
    capability_slug: "apiary-inspection",
    capability_display_name: "蜂箱巡检与计数",
    capability_problem_definition: "识别养蜂场蜂箱与巡检人员，辅助蜂场资产盘点和作业记录。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["蜂场固定机位", "蜂箱近景", "白天自然光视频"],
    capability_unsupported_conditions: ["蜂箱被植被大面积遮挡", "夜间无补光"],
    endpoint_url: "/v1/marketplace/mock-alg-apiary/infer",
    model_name: "YOLO26s",
    model_version_number: 1,
    task_type: "object-detection",
    title: "蜂箱巡检与计数",
    summary: "识别蜂箱和巡检人员，支持蜂场资产盘点与作业记录。",
    category: "农业",
    price_per_1000_cents: 1880,
    monthly_quota_units: 16000,
    is_mock: true,
    preview: {
      scene: "apiary",
      alt: "蜂箱巡检与计数效果样例",
      boxes: [
        { label: "巡检人员", confidence: "0.97", x: 16, y: 10, width: 38, height: 77 },
        { label: "蜂箱", confidence: "0.94", x: 54, y: 23, width: 31, height: 49 },
      ],
    },
    metrics: [
      { label: "mAP50", value: "93.1%" },
      { label: "精确率", value: "94.0%" },
      { label: "召回率", value: "90.2%" },
    ],
    classes: ["蜂箱", "巡检人员", "疑似空箱"],
    model_architecture: "YOLO26s",
    input_size: "1280 × 720",
    latency_p95: "52 ms",
    evaluation_basis: "演示能力卡，无公开基准；正式版本需自建测试集",
    updated_label: "2026-07-27",
  },
];

type MockAlgorithmInput = {
  id: string;
  title: string;
  summary: string;
  slug: string;
  problem: string;
  category: string;
  scene: CatalogScene;
  classes: string[];
  verifiedScenes: string[];
  unsupported: string[];
  boxes: PreviewBox[];
  price: number;
  quota: number;
};

function createMockAlgorithm(input: MockAlgorithmInput): AlgorithmCatalogItem {
  return {
    ...mockProvider,
    ...algorithmDefaults,
    id: input.id,
    deployment_id: `mock-deployment-${input.slug}`,
    capability_spec_id: `mock-capability-${input.slug}`,
    capability_slug: input.slug,
    capability_display_name: input.title,
    capability_problem_definition: input.problem,
    capability_output_contract: "detections.v1",
    capability_verified_scenes: input.verifiedScenes,
    capability_unsupported_conditions: input.unsupported,
    endpoint_url: `/v1/marketplace/${input.id}/infer`,
    model_name: "YOLO26m",
    model_version_number: 1,
    task_type: "object-detection",
    title: input.title,
    summary: input.summary,
    category: input.category,
    price_per_1000_cents: input.price,
    monthly_quota_units: input.quota,
    is_mock: true,
    preview: { scene: input.scene, alt: `${input.title}效果样例`, boxes: input.boxes },
    metrics: [
      { label: "mAP50", value: "待真实训练" },
      { label: "精确率", value: "待真实训练" },
      { label: "召回率", value: "待真实训练" },
    ],
    classes: input.classes,
    model_architecture: "YOLO26m",
    input_size: "1280 × 720",
    latency_p95: "待真实服务",
    evaluation_basis: "演示能力卡，待接入真实训练与独立验收",
    updated_label: "2026-09-06",
  };
}

const ROAD_ALGORITHM_LISTINGS: AlgorithmCatalogItem[] = [
  createMockAlgorithm({ id: "mock-alg-road-surface", title: "路面病害识别", summary: "识别裂缝、坑槽、车辙、沉陷等路面病害，辅助道路巡检。", slug: "road-surface-defects", problem: "从道路巡检图像中发现并分类典型路面病害。", category: "道路工程", scene: "road-surface", classes: ["横向裂缝", "纵向裂缝", "网状裂缝", "坑槽", "车辙", "沉陷", "龟裂", "修补不良"], verifiedScenes: ["车载道路巡检", "沥青与水泥路面", "白天可见光图像"], unsupported: ["夜间无补光", "积雪与严重积水"], boxes: [{ label: "横向裂缝", confidence: "演示", x: 8, y: 40, width: 38, height: 9 }, { label: "坑槽", confidence: "演示", x: 60, y: 52, width: 22, height: 18 }], price: 2480, quota: 18000 }),
  createMockAlgorithm({ id: "mock-alg-road-safety", title: "交安设施异常识别", summary: "发现护栏、防眩板、标志标牌、标线和防撞桶异常。", slug: "road-safety-facilities", problem: "从道路巡检图像中识别交通安全设施缺失、损坏和外观异常。", category: "道路工程", scene: "road-safety", classes: ["护栏缺失", "护栏损坏", "护栏污损", "护栏变形", "防眩板损坏", "防眩板缺失", "标牌反光异常", "标牌倾斜", "标牌污损", "标线不清晰", "轮廓标", "防撞桶"], verifiedScenes: ["高速公路巡检", "国省道路侧", "白天与路灯夜景"], unsupported: ["强逆光", "设施内部结构损伤"], boxes: [{ label: "护栏变形", confidence: "演示", x: 8, y: 47, width: 48, height: 18 }, { label: "标牌倾斜", confidence: "演示", x: 67, y: 12, width: 18, height: 28 }], price: 2280, quota: 20000 }),
  createMockAlgorithm({ id: "mock-alg-road-slope", title: "路基边坡异常识别", summary: "识别滑坡、塌方、冲沟、防护网和挡墙异常。", slug: "road-slope-anomalies", problem: "从山区道路巡检图像中发现边坡和排水设施异常线索。", category: "道路工程", scene: "road-slope", classes: ["滑坡", "塌方", "冲沟", "防护网破损", "挡墙开裂", "挡墙倾斜", "排水沟堵塞"], verifiedScenes: ["山区公路", "雨后边坡", "车载与航拍图像"], unsupported: ["植被完全遮挡", "地质结构内部风险"], boxes: [{ label: "滑坡", confidence: "演示", x: 42, y: 11, width: 42, height: 34 }, { label: "防护网破损", confidence: "演示", x: 12, y: 38, width: 26, height: 27 }], price: 2380, quota: 16000 }),
  createMockAlgorithm({ id: "mock-alg-road-environment", title: "路域环境异常识别", summary: "发现抛洒物、违法占用、绿化遮挡、积水和结冰等路况异常。", slug: "road-environment-anomalies", problem: "从道路巡检图像中发现影响通行和环境的异常目标。", category: "道路工程", scene: "road-environment", classes: ["散落物", "油污", "大件垃圾", "违章堆放", "占道施工", "枝叶侵入", "标志遮挡", "火灾烟雾", "积水", "结冰"], verifiedScenes: ["城市道路", "高速路段", "日常巡检视频"], unsupported: ["严重雨雪", "无法确认的污染成分"], boxes: [{ label: "散落物", confidence: "演示", x: 28, y: 61, width: 17, height: 12 }, { label: "占道施工", confidence: "演示", x: 57, y: 43, width: 31, height: 27 }], price: 2180, quota: 22000 }),
  createMockAlgorithm({ id: "mock-alg-tunnel", title: "隧道设施异常识别", summary: "识别洞口、衬砌、排水和照明风机等隧道设施异常。", slug: "tunnel-facility-anomalies", problem: "从隧道巡检图像中发现设施外观和结构表面异常线索。", category: "道路工程", scene: "tunnel", classes: ["洞口滑坡", "洞口落石", "防护网破损", "衬砌裂缝", "衬砌渗漏水", "衬砌剥落", "背后空洞迹象", "排水沟堵塞", "排水沟积水", "排水沟破损", "照明外观异常", "风机外观异常"], verifiedScenes: ["公路隧道", "洞口与拱顶", "车载巡检图像"], unsupported: ["不可见内部空洞", "无照明极暗画面"], boxes: [{ label: "衬砌裂缝", confidence: "演示", x: 38, y: 21, width: 25, height: 12 }, { label: "渗漏水", confidence: "演示", x: 67, y: 39, width: 15, height: 26 }], price: 2580, quota: 15000 }),
  createMockAlgorithm({ id: "mock-alg-bridge", title: "桥梁设施病害识别", summary: "识别桥面、伸缩缝、支座、墩台和梁体病害。", slug: "bridge-facility-defects", problem: "从桥梁巡检图像中发现构件表面病害和异常线索。", category: "道路工程", scene: "bridge", classes: ["桥面裂缝", "桥面坑槽", "桥面车辙", "伸缩缝堵塞", "伸缩缝损坏", "伸缩缝错位", "支座老化", "支座开裂", "支座脱空", "支座偏位", "墩台冲刷", "混凝土剥落", "钢筋锈蚀", "梁体裂缝", "梁体渗水", "梁体白华"], verifiedScenes: ["公路桥梁", "桥面与墩台", "无人机与近距离图像"], unsupported: ["构件内部损伤", "无法接近的遮挡区域"], boxes: [{ label: "桥面裂缝", confidence: "演示", x: 12, y: 47, width: 37, height: 10 }, { label: "伸缩缝堵塞", confidence: "演示", x: 55, y: 51, width: 24, height: 14 }], price: 2680, quota: 14000 }),
];

const URBAN_ALGORITHM_LISTINGS: AlgorithmCatalogItem[] = [
  createMockAlgorithm({ id: "mock-alg-urban-illegal", title: "违法建设识别", summary: "发现楼顶搭建、露台封闭、阳光房和彩钢房等疑似违建线索。", slug: "urban-illegal-construction", problem: "从航拍与街景图像中发现建筑外观变化和疑似违建线索。", category: "城市治理", scene: "urban-illegal", classes: ["楼顶新增搭建", "露台封闭", "阳光房", "彩钢房", "新建建筑", "外立面明显变化", "疑似违建脚手架", "疑似违建围挡"], verifiedScenes: ["城市航拍", "城乡结合部", "建筑外立面"], unsupported: ["缺少历史对照影像", "无法替代规划执法认定"], boxes: [{ label: "楼顶新增搭建", confidence: "演示", x: 48, y: 12, width: 28, height: 24 }, { label: "彩钢房", confidence: "演示", x: 14, y: 51, width: 27, height: 24 }], price: 2480, quota: 16000 }),
  createMockAlgorithm({ id: "mock-alg-urban-sanitation", title: "市容环境问题识别", summary: "识别占道经营、垃圾堆积、乱贴乱画和非机动车乱停放。", slug: "urban-sanitation-issues", problem: "从网格巡查图像中发现影响市容环境的异常目标。", category: "城市治理", scene: "urban-sanitation", classes: ["占道摊位", "占道棚亭", "游商小贩", "垃圾堆积", "垃圾爆桶", "乱贴乱画", "违规广告", "非机动车乱停放", "店外经营", "店外乱堆放"], verifiedScenes: ["城市街区", "商圈与社区", "网格巡查图像"], unsupported: ["夜间低照度", "不输出商户身份和处罚结论"], boxes: [{ label: "占道摊位", confidence: "演示", x: 8, y: 48, width: 28, height: 28 }, { label: "垃圾爆桶", confidence: "演示", x: 65, y: 58, width: 18, height: 25 }], price: 2280, quota: 20000 }),
  createMockAlgorithm({ id: "mock-alg-urban-construction-waste", title: "建筑垃圾与渣土识别", summary: "发现偷倒乱倒、渣土车抛洒滴漏和露天堆放等问题。", slug: "urban-construction-waste", problem: "从道路和工地周边图像中识别建筑垃圾与渣土异常。", category: "城市治理", scene: "urban-construction-waste", classes: ["建筑垃圾偷倒", "建筑垃圾乱倒", "渣土车抛洒", "渣土车滴漏", "装修垃圾露天堆放", "消纳场违规倾倒"], verifiedScenes: ["工地周边", "城乡结合部", "消纳场卡口"], unsupported: ["不追踪车辆轨迹", "无法单凭图像认定责任主体"], boxes: [{ label: "建筑垃圾偷倒", confidence: "演示", x: 12, y: 49, width: 31, height: 26 }, { label: "渣土车抛洒", confidence: "演示", x: 51, y: 36, width: 34, height: 31 }], price: 2180, quota: 18000 }),
  createMockAlgorithm({ id: "mock-alg-urban-site", title: "工地施工违规识别", summary: "识别施工扬尘、裸土、围挡和出入口污染等违规线索。", slug: "urban-construction-site", problem: "从工地固定机位图像中发现施工环境违规线索。", category: "城市治理", scene: "urban-site", classes: ["可见施工扬尘", "裸土未覆盖", "围挡超范围", "围挡破损", "施工机械违规作业", "黄土裸露", "工地出入口污染"], verifiedScenes: ["房建工地", "道路工地", "工地出入口"], unsupported: ["扬尘受天气影响", "不判断施工许可"], boxes: [{ label: "可见施工扬尘", confidence: "演示", x: 42, y: 9, width: 37, height: 35 }, { label: "围挡破损", confidence: "演示", x: 67, y: 48, width: 22, height: 27 }], price: 2280, quota: 18000 }),
  createMockAlgorithm({ id: "mock-alg-urban-advertising", title: "户外广告与招牌识别", summary: "识别广告牌破损倾斜、广告布脱落和招牌掉落风险。", slug: "urban-advertising-signage", problem: "从街景图像中发现户外广告和店招的外观异常。", category: "城市治理", scene: "urban-advertising", classes: ["广告牌破损", "广告牌倾斜", "广告布脱落", "违规悬挂横幅", "店招破损", "店招掉落风险"], verifiedScenes: ["商业街区", "主次干道", "楼宇外立面"], unsupported: ["不判断广告内容合规性", "不替代结构安全鉴定"], boxes: [{ label: "广告牌倾斜", confidence: "演示", x: 9, y: 15, width: 27, height: 31 }, { label: "广告布脱落", confidence: "演示", x: 56, y: 12, width: 33, height: 27 }], price: 1980, quota: 16000 }),
  createMockAlgorithm({ id: "mock-alg-urban-municipal", title: "市政设施损坏识别", summary: "发现道路破损、井盖异常、路灯和城市家具损坏。", slug: "urban-municipal-damage", problem: "从市政巡查图像中识别道路和公共设施外观损坏。", category: "城市治理", scene: "urban-municipal", classes: ["道路坑槽", "道路破损", "井盖缺失", "井盖移位", "井盖破损", "路灯损坏", "路灯倾斜", "交通护栏损坏", "交通护栏缺失", "座椅破损", "垃圾桶破损"], verifiedScenes: ["城市道路", "人行道", "公园与广场"], unsupported: ["积水遮挡井盖", "不估算维修费用"], boxes: [{ label: "井盖缺失", confidence: "演示", x: 24, y: 58, width: 18, height: 16 }, { label: "路灯倾斜", confidence: "演示", x: 68, y: 7, width: 14, height: 63 }], price: 2180, quota: 20000 }),
  createMockAlgorithm({ id: "mock-alg-urban-water", title: "河道与水域污染识别", summary: "识别漂浮物、油污、禁钓禁泳行为和可见污水直排。", slug: "urban-water-pollution", problem: "从河道和水域巡查图像中发现污染和违规行为线索。", category: "城市治理", scene: "urban-water", classes: ["垃圾漂浮物", "水草漂浮物", "水面油污", "水面彩色污染", "禁钓区垂钓", "禁泳区游泳", "污水直排", "污水偷排"], verifiedScenes: ["城市河道", "湖泊闸口", "排污口巡查"], unsupported: ["不判断污染物成分", "水面强反光"], boxes: [{ label: "垃圾漂浮物", confidence: "演示", x: 16, y: 55, width: 23, height: 16 }, { label: "禁钓区垂钓", confidence: "演示", x: 72, y: 10, width: 15, height: 33 }], price: 2080, quota: 16000 }),
  createMockAlgorithm({ id: "mock-alg-urban-ecology", title: "生态环境问题识别", summary: "识别焚烧烟雾、工地扬尘和裸露地块扬尘。", slug: "urban-ecology-issues", problem: "从生态环境巡查图像中发现烟雾和扬尘视觉线索。", category: "城市治理", scene: "urban-ecology", classes: ["秸秆焚烧烟雾", "垃圾焚烧烟雾", "工地扬尘", "裸露地块扬尘"], verifiedScenes: ["城乡结合部", "农田与裸地", "工地周边"], unsupported: ["雾霾和云雾干扰", "不判断排放浓度"], boxes: [{ label: "秸秆焚烧烟雾", confidence: "演示", x: 18, y: 20, width: 30, height: 34 }, { label: "工地扬尘", confidence: "演示", x: 58, y: 40, width: 30, height: 27 }], price: 1880, quota: 16000 }),
  createMockAlgorithm({ id: "mock-alg-urban-fire", title: "火情与安全隐患识别", summary: "识别明火、浓烟、火灾蔓延迹象和易燃物违规堆放。", slug: "urban-fire-hazards", problem: "从城市监控图像中发现火情和安全隐患视觉线索。", category: "城市治理", scene: "urban-fire", classes: ["明火", "浓烟", "火灾蔓延迹象", "易燃物违规堆放"], verifiedScenes: ["社区与商铺", "工地与仓储", "室内外监控"], unsupported: ["不替代消防报警器", "强光反射干扰"], boxes: [{ label: "明火", confidence: "演示", x: 48, y: 47, width: 18, height: 27 }, { label: "浓烟", confidence: "演示", x: 37, y: 10, width: 36, height: 40 }], price: 2080, quota: 18000 }),
  createMockAlgorithm({ id: "mock-alg-urban-crowd", title: "人员聚集与公共安全识别", summary: "识别异常聚集、拥堵、突发事件现场和人流密度异常。", slug: "urban-crowd-safety", problem: "从公共空间监控图像中发现人群密度和秩序异常线索。", category: "城市治理", scene: "urban-crowd", classes: ["人员异常聚集", "人群拥堵", "突发事件现场", "人流密度异常"], verifiedScenes: ["商圈广场", "车站出入口", "大型活动场地"], unsupported: ["不识别个人身份", "密度阈值需按场所配置"], boxes: [{ label: "人员异常聚集", confidence: "演示", x: 30, y: 35, width: 40, height: 35 }, { label: "人群拥堵", confidence: "演示", x: 58, y: 57, width: 31, height: 27 }], price: 2280, quota: 18000 }),
  createMockAlgorithm({ id: "mock-alg-urban-traffic", title: "交通与停车秩序识别", summary: "识别禁停区违法停车、应急车道占用和无警示占道施工。", slug: "urban-traffic-order", problem: "从道路监控图像中发现停车和施工秩序异常线索。", category: "城市治理", scene: "urban-traffic", classes: ["禁停区违法停车", "应急车道占用", "交通拥堵", "占道施工无警示"], verifiedScenes: ["城市道路", "高速应急车道", "施工路段"], unsupported: ["不输出处罚结论", "需结合道路规则配置"], boxes: [{ label: "禁停区违法停车", confidence: "演示", x: 12, y: 55, width: 30, height: 22 }, { label: "占道施工无警示", confidence: "演示", x: 65, y: 18, width: 24, height: 28 }], price: 2180, quota: 20000 }),
  createMockAlgorithm({ id: "mock-alg-urban-greening", title: "园林绿化问题识别", summary: "识别毁绿种菜、树木倒伏折断、绿化带垃圾和黄土裸露。", slug: "urban-greening-issues", problem: "从公园和道路绿化巡查图像中发现绿化养护异常。", category: "城市治理", scene: "urban-greening", classes: ["毁绿种菜", "树木倒伏", "树木折断", "绿化带垃圾堆积", "绿地黄土裸露"], verifiedScenes: ["城市公园", "道路绿化带", "社区绿地"], unsupported: ["季节性养护混淆", "不评估树木健康等级"], boxes: [{ label: "毁绿种菜", confidence: "演示", x: 14, y: 54, width: 28, height: 22 }, { label: "树木倒伏", confidence: "演示", x: 51, y: 40, width: 35, height: 19 }], price: 1880, quota: 16000 }),
];

export const MOCK_ALGORITHM_LISTINGS: AlgorithmCatalogItem[] = [
  ...CORE_MOCK_ALGORITHM_LISTINGS,
  ...ROAD_ALGORITHM_LISTINGS,
  ...URBAN_ALGORITHM_LISTINGS,
];

function qualityReport(
  id: string,
  assetCount: number,
  classes: string[],
  coverage: number,
  advisories: string[],
): DatasetVersionQualityReport {
  const valid = Math.round(assetCount * 0.15);
  const test = Math.round(assetCount * 0.1);
  const train = assetCount - valid - test;
  return {
    dataset_version_id: id,
    schema_version: "1.0",
    asset_count: assetCount,
    split_counts: { train, valid, test },
    annotated_asset_count: Math.round(assetCount * coverage / 100),
    unannotated_asset_count: assetCount - Math.round(assetCount * coverage / 100),
    annotation_coverage_percent: coverage,
    class_distribution: classes.map((className, index) => ({
      class_id: index,
      class_name: className,
      annotation_count: Math.max(120, Math.round(assetCount * (1.25 - index * 0.12))),
      asset_count: Math.max(90, Math.round(assetCount * (0.72 - index * 0.07))),
    })),
    image_dimensions: {
      known_asset_count: assetCount,
      unknown_asset_count: 0,
      min_width: 640,
      max_width: 3840,
      min_height: 480,
      max_height: 2160,
    },
    advisories,
  };
}

const dataDefaults = {
  ...mockProvider,
  project_name: "SenseMu 数据精选",
  review_basis: "provider_attestation" as const,
  status: "published" as const,
  delivery_mode: "workspace_copy_after_authorization" as const,
  delivery_status: "prepared_not_open" as const,
  delivery_spec_hash: null,
  published_at: "2026-08-01T08:00:00Z",
  allow_derivative_models: true,
  allow_redistribution: false,
  contains_personal_data: false,
  privacy_treatment: "不包含可识别个人身份的信息；人像已做脱敏或只用于目标框标注。",
  custom_license_terms: null,
};

const dataSceneCategories: Record<CatalogScene, string> = {
  ppe: "安全生产",
  fire: "安全生产",
  traffic: "智慧交通",
  defect: "工业质检",
  parcel: "仓储物流",
  shelf: "智慧零售",
  forest: "林业",
  "forest-fire": "林业",
  crop: "农业",
  orchard: "农业",
  apiary: "农业",
  "road-surface": "道路工程",
  "road-safety": "道路工程",
  "road-slope": "道路工程",
  "road-environment": "道路工程",
  tunnel: "道路工程",
  bridge: "道路工程",
  "urban-illegal": "城市治理",
  "urban-sanitation": "城市治理",
  "urban-construction-waste": "城市治理",
  "urban-site": "城市治理",
  "urban-advertising": "城市治理",
  "urban-municipal": "城市治理",
  "urban-water": "城市治理",
  "urban-ecology": "城市治理",
  "urban-fire": "城市治理",
  "urban-crowd": "城市治理",
  "urban-traffic": "城市治理",
  "urban-greening": "城市治理",
};

function dataListing(input: {
  id: string;
  scene: CatalogScene;
  title: string;
  summary: string;
  taskType: string;
  assetCount: number;
  classes: string[];
  source: string;
  method: string;
  coverage: string;
  limitations: string;
  license: DataMarketListing["license_code"];
  commercial: boolean;
  price: string;
  annotationType: string;
  imageSize: string;
  imageUrl?: string;
  aspectRatio?: number;
  boxes: PreviewBox[];
  coveragePercent: number;
  advisories: string[];
}): DataCatalogItem {
  const versionId = `${input.id}-v2`;
  return {
    ...dataDefaults,
    id: input.id,
    dataset_version_id: versionId,
    dataset_id: `${input.id}-dataset`,
    dataset_name: input.title,
    dataset_version_number: 2,
    task_type: input.taskType,
    asset_count: input.assetCount,
    class_map: Object.fromEntries(input.classes.map((name, index) => [String(index), name])),
    quality_report: qualityReport(versionId, input.assetCount, input.classes, input.coveragePercent, input.advisories),
    title: input.title,
    summary: input.summary,
    source_summary: input.source,
    collection_method: input.method,
    coverage_summary: input.coverage,
    known_limitations: input.limitations,
    license_code: input.license,
    allow_commercial_use: input.commercial,
    allow_model_training: true,
    preview: {
      scene: input.scene,
      alt: `${input.title}标注样例`,
      image_url: input.imageUrl,
      aspect_ratio: input.aspectRatio,
      boxes: input.boxes,
    },
    scene_category: dataSceneCategories[input.scene],
    price_label: input.price,
    annotation_type: input.annotationType,
    image_size_summary: input.imageSize,
    updated_label: "2026-09",
    is_mock: true,
  };
}

export const MOCK_DATA_LISTINGS: DataCatalogItem[] = [
  dataListing({
    id: "mock-data-ppe",
    scene: "ppe",
    title: "工地安全穿戴数据集",
    summary: "覆盖安全帽、反光衣和人员目标，适合训练工地安全检测模型。",
    taskType: "object-detection",
    assetCount: 8099,
    classes: ["人员", "安全帽", "未戴安全帽", "反光衣", "未穿反光衣"],
    source: "公开数据集 SH17（github.com/ahmadmughees/sh17dataset，arXiv:2407.04590）：8,099 张真实工业环境图像、75,994 个标注实例、17 类安全穿戴与人体部位目标。",
    method: "多地域真实场景采集，单图逐目标人工框选；作者提供逐图来源元数据与开源基线权重。",
    coverage: "覆盖室内外制造与施工环境、不同人像距离和密度，类别含安全帽、护目镜、口罩、反光衣、安全鞋等 17 类。",
    limitations: "许可为 CC BY-NC-SA 4.0，仅限非商业研究用途；夜间无补光与极远距离人员样本较少。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "公开数据集免费获取",
    annotationType: "目标框",
    imageSize: "640p–4K",
    boxes: MOCK_ALGORITHM_LISTINGS[0].preview.boxes.map(({ label, x, y, width, height }) => ({ label, x, y, width, height })),
    coveragePercent: 99.2,
    advisories: ["夜间样本占比 8.4%，部署到夜间场景前建议补充采样。"],
  }),
  dataListing({
    id: "mock-data-fire",
    scene: "fire",
    title: "仓储烟火异常数据集",
    summary: "烟雾、明火与正常蒸汽对照数据，用于仓储风险识别。",
    taskType: "object-detection",
    assetCount: 21527,
    classes: ["烟雾", "明火", "蒸汽"],
    source: "公开数据集 D-Fire（github.com/gaiasd/DFireDataset）：21,527 张图像，含仅明火 1,164 张、仅烟雾 5,867 张、火烟共存 4,658 张及 9,838 张负样本对照。",
    method: "互联网真实场景、火灾模拟与监控画面整合，YOLO 格式框标注（明火 14,692 框、烟雾 11,865 框），官方提供训练/验证/测试划分。",
    coverage: "覆盖室内外监控视角、远距离小火点与多样烟雾形态，大量负样本用于抑制误报。",
    limitations: "原始许可为研究用途授权（引用 Venâncio et al., Neural Computing & Applications 2022）；不包含红外热成像。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "公开数据集免费获取",
    annotationType: "目标框",
    imageSize: "720p–1080p",
    boxes: MOCK_ALGORITHM_LISTINGS[1].preview.boxes.map(({ label, x, y, width, height }) => ({ label, x, y, width, height })),
    coveragePercent: 98.7,
    advisories: ["蒸汽对照样本集中于室内环境。"],
  }),
  dataListing({
    id: "mock-data-traffic",
    scene: "traffic",
    title: "城市路口车辆数据集",
    summary: "多城市固定高位相机采集的车辆检测与分类数据。",
    taskType: "object-detection",
    assetCount: 100000,
    classes: ["小客车", "货车", "公交车", "摩托车", "自行车"],
    source: "公开数据集 BDD100K（bdd-data.berkeley.edu）：10 万段真实驾驶场景图像；可另用 UA-DETRAC（城市交通监控，10 万+ 帧）补充。",
    method: "行车记录仪与监控真实街景，人工框选车辆类别；UA-DETRAC 提供逐帧车辆框标注。",
    coverage: "覆盖白天/夜间、晴/雨/雾、城市街道与高速等多条件驾驶场景。",
    limitations: "BDD100K 许可为非商业研究用途；商用需自行处理车牌与行人隐私信息。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "公开数据集免费获取",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: MOCK_ALGORITHM_LISTINGS[2].preview.boxes.map(({ label, x, y, width, height }) => ({ label, x, y, width, height })),
    coveragePercent: 99.6,
    advisories: ["夜间摩托车样本量低于其他类别。"],
  }),
  dataListing({
    id: "mock-data-defect",
    scene: "defect",
    title: "金属表面缺陷数据集",
    summary: "钢板与铝板表面的划痕、凹坑和氧化区域精细标注。",
    taskType: "segmentation",
    assetCount: 4100,
    classes: ["划痕", "凹坑", "氧化"],
    source: "公开数据集 NEU-DET（东北大学热轧钢带表面缺陷，1,800 张 6 类）与 GC10-DET（金属表面缺陷，约 2,300 张 10 类）。",
    method: "产线标准条件下采集，目标框标注；NEU-DET 含裂纹、夹杂、斑块、麻点、氧化皮、划痕六类典型缺陷。",
    coverage: "覆盖热轧钢带与多种金属表面的划痕、斑块、氧化皮、麻点等典型缺陷。",
    limitations: "原始许可为学术研究用途；像素级分割可参照 Severstal 钢材缺陷数据（Kaggle）另行获取。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "公开数据集免费获取",
    annotationType: "多边形分割",
    imageSize: "2048 × 2048",
    boxes: MOCK_ALGORITHM_LISTINGS[3].preview.boxes.map(({ label, x, y, width, height }) => ({ label, x, y, width, height })),
    coveragePercent: 100,
    advisories: ["凹坑类别占比为 12.6%，存在轻度不均衡。"],
  }),
  dataListing({
    id: "mock-data-parcel",
    scene: "parcel",
    title: "物流包裹传送带数据集",
    summary: "纸箱、软包和编织袋在分拣线上的检测标注数据。",
    taskType: "object-detection",
    assetCount: 600,
    classes: ["纸箱", "软包", "编织袋"],
    source: "公开社区数据集 Wisdom Logistics Express Parcel Damage（GitHub 仓库公开 README 预览图；约 1,340 张、含 package / Damaged 类）。完整原始文件需向作者申请，授权待核验。",
    method: "当前卡片使用作者 README 的数据集预览图，不把拼图预览当作可下载原始训练图片；正式接入前需获取原始文件、校验授权与 checksum。",
    coverage: "覆盖不同传送带颜色、俯拍角度、包裹尺寸与堆叠程度（演示样例）。",
    limitations: "当前只展示社区仓库公开预览图，不能作为训练数据商品或授权证明；完整数据与商业许可待核验。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "演示样例，正式版本另议",
    annotationType: "目标框",
    imageSize: "720p–2K",
    boxes: MOCK_ALGORITHM_LISTINGS[4].preview.boxes.map(({ label, x, y, width, height }) => ({ label, x, y, width, height })),
    coveragePercent: 99.8,
    advisories: [],
  }),
  dataListing({
    id: "mock-data-shelf",
    scene: "shelf",
    title: "零售货架缺货数据集",
    summary: "商超货架空位、低库存与正常陈列的区域标注数据。",
    taskType: "object-detection",
    assetCount: 11762,
    classes: ["缺货区域", "低库存区域", "正常陈列"],
    source: "公开数据集 SKU-110K（github.com/eg4000/SKU110K_CVPR19）：11,762 张真实商超货架图像、170 万+ 密集商品框标注。当前卡片使用官方 qualitative 结果预览图。",
    method: "真实零售货架密集商品目标框标注，官方提供训练/验证/测试划分；卡片展示图是官方项目预览拼图，不代表单张原始样本。",
    coverage: "覆盖多家商超的真实货架、密集商品陈列与不同拍摄角度。",
    limitations: "SKU-110K 许可为研究用途，商用需联系作者授权；缺货区域专用标签需二次标注。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "公开数据集免费获取",
    annotationType: "区域框",
    imageSize: "1080p–4K",
    boxes: MOCK_ALGORITHM_LISTINGS[5].preview.boxes.map(({ label, x, y, width, height }) => ({ label, x, y, width, height })),
    coveragePercent: 98.9,
    advisories: ["正常陈列类别数量较多，训练时建议使用类别权重。"],
  }),
  dataListing({
    id: "mock-data-forest-health",
    scene: "forest",
    title: "林区树木健康数据集",
    summary: "林区航拍与固定机位图像，标注健康、枯死和倒伏树木。",
    taskType: "object-detection",
    assetCount: 500,
    classes: ["健康树木", "疑似枯死树", "倒伏树木", "病害斑块"],
    source: "Open Images V7 树木/绿地图像（CC BY 2.0）用于展示公开真实样本；林木健康、枯死和倒伏标签仍需按林业巡检规范二次采集与标注。",
    method: "卡片展示 Open Images 原始照片，框线为 SenseMu Mock 演示；正式版本需接入林区航拍或固定机位数据并独立验收。",
    coverage: "覆盖针叶林、阔叶林、林缘与林道，以及晴天和阴天光照（演示样例）。",
    limitations: "社区数据规模与许可参差不齐，本卡当前为演示数据，不承诺样本出处。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "演示样例，正式版本另议",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [
      { label: "疑似枯死树", x: 4, y: 20, width: 18, height: 63 },
      { label: "倒伏树木", x: 67, y: 54, width: 25, height: 18 },
    ],
    coveragePercent: 96.4,
    advisories: ["冬季落叶林样本占比 11.2%，跨季节部署前建议补充验证。"],
  }),
  dataListing({
    id: "mock-data-forest-fire",
    scene: "forest-fire",
    title: "森林烟火监控数据集",
    summary: "林区烟雾、火点与云雾反光对照数据，用于早期火情识别。",
    taskType: "object-detection",
    assetCount: 21527,
    classes: ["烟雾", "火点", "云雾", "高亮反光"],
    source: "D-Fire（github.com/gaia-solutions-on-demand/DFireDataset）与 FLAME 公开研究数据集用于能力定义；卡片展示的是可追溯的 Open Images CC BY 2.0 火情照片。",
    method: "卡片展示 Open Images 原始照片，框线为 SenseMu Mock 演示；真实 D-Fire / FLAME 训练样本需按其研究授权单独入库。",
    coverage: "覆盖野外/林地火点、远距离烟柱与负样本对照。",
    limitations: "D-Fire 为研究用途授权，FLAME 需 IEEE Dataport 注册获取；负样本以城市背景为主。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "公开数据集免费获取",
    annotationType: "目标框",
    imageSize: "720p–4K",
    boxes: [{ label: "烟雾", x: 49, y: 4, width: 38, height: 30 }],
    coveragePercent: 98.1,
    advisories: ["云雾与烟雾对照样本已分层，但仍建议结合现场阈值复核。"],
  }),
  dataListing({
    id: "mock-data-produce",
    scene: "crop",
    title: "农产品分选数据集",
    summary: "蔬果品类与明显外观缺陷标注，适合收购与分选台训练。",
    taskType: "object-detection",
    assetCount: 90483,
    classes: ["苹果", "香蕉", "黄瓜", "胡萝卜", "辣椒", "疑似外观缺陷"],
    source: "公开数据集 Fruits-360（github.com/Horea94/Fruit-Images-Dataset）：约 9 万张蔬果图像、130+ 品类；当前卡片使用 Apple Braeburn 原始样本。",
    method: "白底单果与真实场景拍摄结合，品类分类标注；新鲜/变质对照需二次标注。",
    coverage: "覆盖苹果、香蕉、黄瓜、胡萝卜、辣椒等 130+ 品类的单果与堆放场景。",
    limitations: "Fruits-360 以白底单果为主，分选台密集堆叠场景需自行采集补充；许可为研究与教学用途。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "公开数据集免费获取",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [
      { label: "苹果", x: 15, y: 14, width: 70, height: 70 },
    ],
    coveragePercent: 99.1,
    advisories: ["疑似外观缺陷类别已单独标注，适合先做人工复核再用于自动分选。"],
  }),
  dataListing({
    id: "mock-data-orchard",
    scene: "orchard",
    title: "果园果实计数数据集",
    summary: "果园行间与树冠近景的果实、未成熟果和病果标注数据。",
    taskType: "object-detection",
    assetCount: 1349,
    classes: ["果实", "未成熟果", "病果"],
    source: "公开数据集 MinneApple（arxiv.org/abs/1905.11451）：1,349 张高分辨率果园图像、7 万+ 果实实例框标注。",
    method: "无人机行间拍摄，果实目标框标注并提供官方 train/val/test 划分与基线。",
    coverage: "覆盖苹果园行间视角、不同密度树冠与自然光照。",
    limitations: "MinneApple 许可为学术研究用途且以苹果为主；其他果品类需自行扩充。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "公开数据集免费获取",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [
      { label: "果实", x: 43, y: 20, width: 12, height: 17 },
      { label: "果实", x: 58, y: 34, width: 14, height: 18 },
      { label: "病果", x: 22, y: 44, width: 13, height: 17 },
    ],
    coveragePercent: 97.8,
    advisories: ["病果类别占比 8.6%，训练时建议使用类别权重。"],
  }),
  dataListing({
    id: "mock-data-apiary",
    scene: "apiary",
    title: "蜂场巡检数据集",
    summary: "蜂箱、巡检人员与疑似空箱标注数据，适合蜂场资产盘点。",
    taskType: "object-detection",
    assetCount: 640,
    classes: ["蜂箱", "巡检人员", "疑似空箱"],
    source: "公开社区数据集 Picking honey Scene Bawah Bee Detection（GitHub 仓库声明 6,640 张、bees 单类）；当前卡片使用 README 公开预览图，完整原始文件与授权待核验。",
    method: "卡片展示社区仓库预览拼图，框线为 SenseMu Mock 演示；正式版本需获取原始单图和许可凭证。",
    coverage: "覆盖蜂箱排列、植被背景、作业人员进入和白天自然光（演示样例）。",
    limitations: "当前只展示社区仓库公开预览图，不能作为训练数据商品或商业授权证明。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "演示样例，正式版本另议",
    annotationType: "目标框",
    imageSize: "1080p–2K",
    boxes: [
      { label: "巡检人员", x: 16, y: 10, width: 38, height: 77 },
      { label: "蜂箱", x: 54, y: 23, width: 31, height: 49 },
    ],
    coveragePercent: 98.5,
    advisories: ["疑似空箱标签来自巡检记录，部署后建议与蜂场台账联动复核。"],
  }),
  dataListing({
    id: "mock-data-road-surface",
    scene: "road-surface",
    title: "路面病害识别数据集",
    summary: "覆盖裂缝、坑槽、车辙与沉陷等典型路面病害，服务道路巡检与养护优先级判断。",
    taskType: "object-detection",
    assetCount: 47420,
    classes: ["横向裂缝", "纵向裂缝", "网状裂缝", "坑槽", "车辙", "沉陷", "龟裂", "修补不良"],
    source: "公开数据集 RDD2022（figshare 21431547，arXiv:2209.08538）：47,420 张真实道路图像、55,000+ 病害实例，覆盖中国、日本、印度、捷克、挪威、美国。",
    method: "车载采集，纵向/横向/龟裂裂缝与坑槽框标注，官方提供逐国划分；可另用 GAPs、CrackForest 补充。",
    coverage: "覆盖六国多种路面材质、气候与拍摄设备（含中国无人机与车载子集）。",
    limitations: "许可为 CC BY-SA 4.0；美国子集源自 Google 街景仅限非商业使用；车辙/沉陷类不在标注体系内，需二次标注。",
    license: "CC-BY-SA-4.0",
    commercial: true,
    price: "公开数据集免费获取",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [
      { label: "横向裂缝", x: 8, y: 40, width: 38, height: 9 },
      { label: "坑槽", x: 60, y: 52, width: 22, height: 18 },
      { label: "车辙", x: 31, y: 68, width: 28, height: 11 },
    ],
    coveragePercent: 98.3,
    advisories: ["网状裂缝与龟裂存在视觉相似，建议结合道路养护规范复核。"],
  }),
  dataListing({
    id: "mock-data-road-safety",
    scene: "road-safety",
    title: "交安设施识别数据集",
    summary: "识别护栏、防眩板、标志标牌、标线、轮廓标和防撞桶的缺失与损坏状态。",
    taskType: "object-detection",
    assetCount: 1600,
    classes: ["波形梁护栏缺失", "波形梁护栏损坏", "混凝土护栏污损", "护栏变形", "防眩板损坏", "防眩板缺失", "标志反光异常", "标牌倾斜", "标牌污损", "标线不清晰", "轮廓标", "防撞桶"],
    source: "部分可映射公开数据：TTPLA（交通标志牌航拍，约 940 张）与 GTSDB/CCTSDB（交通标志检测）；护栏/防眩板无公开数据集。",
    method: "交通标志部分可使用上述公开标注；护栏类当前为演示样例，需自有巡检数据标注。",
    coverage: "覆盖中央分隔带、路侧、匝道和收费站前后（标志类为真实公开数据）。",
    limitations: "护栏/防眩板/防撞桶无公开数据集，本卡该部分为演示数据，不承诺样本出处。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "演示样例，正式版本另议",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [
      { label: "护栏变形", x: 8, y: 47, width: 48, height: 18 },
      { label: "标牌倾斜", x: 67, y: 12, width: 18, height: 28 },
      { label: "防撞桶", x: 74, y: 66, width: 11, height: 20 },
    ],
    coveragePercent: 97.6,
    advisories: ["标志反光异常依赖采集角度，采购前建议核对现场验收标准。"],
  }),
  dataListing({
    id: "mock-data-road-slope",
    scene: "road-slope",
    title: "路基边坡异常数据集",
    summary: "覆盖滑坡、塌方、冲沟、防护网和挡墙异常，支持汛期巡检与风险排查。",
    taskType: "object-detection",
    assetCount: 3799,
    classes: ["滑坡", "塌方", "冲沟", "防护网破损", "挡墙开裂", "挡墙倾斜", "排水沟堵塞"],
    source: "公开数据集 Landslide4Sense（IEEE DataPort）：3,799 个多光谱卫星滑坡区块（128×128）；可见光滑坡数据学界另有散在公开集。",
    method: "Sentinel-2 多光谱影像切片，滑坡/非滑坡二值标注，官方提供 train/valid/test 划分。",
    coverage: "覆盖全球多区域滑坡与常态地形对照。",
    limitations: "为卫星多光谱切片而非路面可见光巡检图像，模态与巡检相机不同；许可为研究用途。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "公开数据集免费获取",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [
      { label: "滑坡", x: 42, y: 11, width: 42, height: 34 },
      { label: "防护网破损", x: 12, y: 38, width: 26, height: 27 },
      { label: "排水沟堵塞", x: 54, y: 72, width: 32, height: 13 },
    ],
    coveragePercent: 96.8,
    advisories: ["雨后样本占比 28.5%，旱季部署前建议补充常态样本。"],
  }),
  dataListing({
    id: "mock-data-road-environment",
    scene: "road-environment",
    title: "路域环境异常数据集",
    summary: "识别抛洒物、违法占用、绿化遮挡及烟雾、积水、结冰等异常路况。",
    taskType: "object-detection",
    assetCount: 1500,
    classes: ["散落物", "油污", "大件垃圾", "违章堆放", "占道施工", "枝叶侵入", "标志遮挡", "火灾烟雾", "积水", "结冰"],
    source: "部分可映射公开数据：TACO（野内外垃圾，约 1,500 张、28 类，CC BY 4.0）与 ACDC（恶劣路况，非商业研究）；散落物/占道施工无专属公开集。",
    method: "垃圾散落部分可使用 TACO 目标框标注；其余类别当前为演示样例，需自有巡检数据标注。",
    coverage: "主干路与匝道巡检场景；垃圾类为真实公开数据，其余为演示样例。",
    limitations: "仅垃圾类有可靠公开标注，占道施工/积水/结冰为演示数据，不承诺样本出处。",
    license: "CC-BY-4.0",
    commercial: true,
    price: "公开数据集免费获取",
    annotationType: "目标框",
    imageSize: "720p–4K",
    boxes: [
      { label: "散落物", x: 28, y: 61, width: 17, height: 12 },
      { label: "占道施工", x: 57, y: 43, width: 31, height: 27 },
      { label: "枝叶侵入", x: 7, y: 7, width: 25, height: 34 },
    ],
    coveragePercent: 98,
    advisories: ["结冰样本较少，低温地区上线前应使用本地数据进行阈值校准。"],
  }),
  dataListing({
    id: "mock-data-tunnel",
    scene: "tunnel",
    title: "隧道设施异常数据集",
    summary: "覆盖洞口边坡、衬砌、排水和机电设施外观异常，适合隧道日常巡检。",
    taskType: "object-detection",
    assetCount: 800,
    classes: ["洞口滑坡", "洞口落石", "防护网破损", "衬砌裂缝", "衬砌渗漏水", "衬砌剥落", "背后空洞迹象", "排水沟堵塞", "排水沟积水", "排水沟破损", "照明外观异常", "风机外观异常"],
    source: "暂无权威公开数据集；学界隧道衬砌裂缝数据多为论文附帽数据，需向作者申请。",
    method: "当前标注为演示样例；正式版本需采集自有隧道巡检画面并标注。",
    coverage: "覆盖洞口、拱顶、边墙、路面排水和照明风机（演示样例）。",
    limitations: "本卡当前为演示数据，不承诺样本出处；背后空洞仅标注可见迹象，不替代无损检测。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "演示样例，正式版本另议",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [
      { label: "衬砌裂缝", x: 38, y: 21, width: 25, height: 12 },
      { label: "渗漏水", x: 67, y: 39, width: 15, height: 26 },
      { label: "照明外观异常", x: 10, y: 11, width: 16, height: 13 },
    ],
    coveragePercent: 97.1,
    advisories: ["隧道内低照度样本已覆盖，但严重积水和烟尘条件仍需现场复核。"],
  }),
  dataListing({
    id: "mock-data-bridge",
    scene: "bridge",
    title: "桥梁设施病害数据集",
    summary: "识别桥面、伸缩缝、支座、墩台与梁体病害，辅助桥梁巡检建档。",
    taskType: "object-detection",
    assetCount: 58000,
    classes: ["桥面裂缝", "桥面坑槽", "桥面车辙", "伸缩缝堵塞", "伸缩缝损坏", "伸缩缝错位", "支座老化", "支座开裂", "支座脱空", "支座偏位", "墩台冲刷", "混凝土剥落", "钢筋锈蚀", "梁体裂缝", "梁体渗水", "梁体白华"],
    source: "公开数据集 CODEBRIM（桥梁表观病害多标签，1,569 张高分辨率、6 类）与 SDNET2018（混凝土裂缝，5.6 万+ 张）。",
    method: "CODEBRIM 提供裂缝/剥落/锈蚀/白华/风化/露筋多标签标注；SDNET2018 提供有缝/无缝二分类。",
    coverage: "覆盖桥面、梁体、墩台等混凝土构件的表观病害。",
    limitations: "均为研究用途许可；伸缩缝/支座类病害无公开标注，本卡该部分为演示数据。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "公开数据集免费获取",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [
      { label: "桥面裂缝", x: 12, y: 47, width: 37, height: 10 },
      { label: "伸缩缝堵塞", x: 55, y: 51, width: 24, height: 14 },
      { label: "混凝土剥落", x: 74, y: 14, width: 15, height: 28 },
    ],
    coveragePercent: 97.9,
    advisories: ["支座类病害存在类别不均衡，训练时建议按构件分层抽样。"],
  }),
  dataListing({
    id: "mock-data-urban-illegal",
    scene: "urban-illegal",
    title: "违法建设识别数据集",
    summary: "识别楼顶新增搭建、露台封闭、阳光房和彩钢房等疑似违法建设变化。",
    taskType: "object-detection",
    assetCount: 600,
    classes: ["楼顶新增搭建", "露台封闭", "阳光房", "彩钢房", "新建建筑", "外立面明显变化", "疑似违建脚手架", "疑似违建围挡"],
    source: "暂无公开数据集（违建识别依赖历史影像比对，学界无公开基准）；需自有航拍/街景两期影像采集。",
    method: "当前标注为演示样例；正式版本需结合两期历史影像做变化检测标注。",
    coverage: "覆盖老城区、城乡结合部、园区和住宅屋顶（演示样例）。",
    limitations: "本卡当前为演示数据，不承诺样本出处；疑似标签不等同于执法认定。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "演示样例，正式版本另议",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [{ label: "楼顶新增搭建", x: 48, y: 12, width: 28, height: 24 }, { label: "彩钢房", x: 14, y: 51, width: 27, height: 24 }, { label: "外立面明显变化", x: 70, y: 38, width: 19, height: 39 }],
    coveragePercent: 96.9,
    advisories: ["模型结果用于线索发现，正式认定需结合规划审批和现场核查。"],
  }),
  dataListing({
    id: "mock-data-urban-sanitation",
    scene: "urban-sanitation",
    title: "市容环境问题数据集",
    summary: "覆盖占道经营、游商小贩、垃圾堆积、乱贴乱画和非机动车乱停放。",
    taskType: "object-detection",
    assetCount: 1500,
    classes: ["占道摊位", "占道棚亭", "游商小贩", "垃圾堆积", "垃圾爆桶", "乱贴乱画", "违规广告", "非机动车乱停放", "店外经营", "店外乱堆放"],
    source: "部分可映射公开数据：TACO（街面垃圾，约 1,500 张、28 类，CC BY 4.0）；占道经营/乱停放无公开数据集。",
    method: "垃圾堆积部分可使用 TACO 标注；占道经营等类别当前为演示样例。",
    coverage: "主次干道、背街小巷、商圈和居民区；垃圾类为真实公开数据，其余为演示样例。",
    limitations: "仅垃圾类有可靠公开标注，占道/乱贴乱画/乱停放为演示数据，不承诺样本出处。",
    license: "CC-BY-4.0",
    commercial: true,
    price: "公开数据集免费获取",
    annotationType: "目标框",
    imageSize: "720p–4K",
    boxes: [{ label: "占道摊位", x: 8, y: 48, width: 28, height: 28 }, { label: "垃圾爆桶", x: 65, y: 58, width: 18, height: 25 }, { label: "非机动车乱停放", x: 39, y: 70, width: 23, height: 16 }],
    coveragePercent: 98.2,
    advisories: ["垃圾堆积和正常临时摆放存在边界，建议结合区域规则复核。"],
  }),
  dataListing({
    id: "mock-data-urban-construction-waste",
    scene: "urban-construction-waste",
    title: "建筑垃圾与渣土数据集",
    summary: "识别建筑垃圾偷倒、渣土车抛洒滴漏、装修垃圾露天堆放和违规倾倒。",
    taskType: "object-detection",
    assetCount: 700,
    classes: ["建筑垃圾偷倒", "建筑垃圾乱倒", "渣土车抛洒", "渣土车滴漏", "装修垃圾露天堆放", "消纳场违规倾倒"],
    source: "暂无权威公开数据集；TACO 含少量建筑垃圾类别样本，场景级偷倒/抛洒需自有卡口数据。",
    method: "当前标注为演示样例；正式版本需采集自有巡查/卡口画面并标注。",
    coverage: "覆盖工地出入口、城乡结合部、河道沿线和消纳场（演示样例）。",
    limitations: "本卡当前为演示数据，不承诺样本出处；不识别车牌或追踪车辆轨迹。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "演示样例，正式版本另议",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [{ label: "建筑垃圾偷倒", x: 12, y: 49, width: 31, height: 26 }, { label: "渣土车抛洒", x: 51, y: 36, width: 34, height: 31 }, { label: "装修垃圾露天堆放", x: 63, y: 68, width: 24, height: 18 }],
    coveragePercent: 97.3,
    advisories: ["夜间卡口样本占比 14.8%，部署前建议按摄像头补充夜间验证。"],
  }),
  dataListing({
    id: "mock-data-urban-site",
    scene: "urban-site",
    title: "工地施工违规数据集",
    summary: "覆盖施工扬尘、裸土未覆盖、围挡违规、机械违规作业和出入口污染。",
    taskType: "object-detection",
    assetCount: 8099,
    classes: ["可见施工扬尘", "裸土未覆盖", "围挡超范围", "围挡破损", "施工机械违规作业", "黄土裸露", "工地出入口污染"],
    source: "部分可映射公开数据：SH17（工地人员与 PPE，8,099 张，CC BY-NC-SA 4.0）；扬尘/裸土/围挡无公开数据集。",
    method: "人员/PPE 部分可使用 SH17 标注；扬尘、裸土、围挡类别当前为演示样例。",
    coverage: "房建、市政、道路工地；PPE 类为真实公开数据，其余为演示样例。",
    limitations: "SH17 为非商业许可；扬尘/围挡类为演示数据，不承诺样本出处。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "公开数据集免费获取",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [{ label: "可见施工扬尘", x: 42, y: 9, width: 37, height: 35 }, { label: "裸土未覆盖", x: 11, y: 60, width: 29, height: 20 }, { label: "围挡破损", x: 67, y: 48, width: 22, height: 27 }],
    coveragePercent: 97.8,
    advisories: ["扬尘与雾霾存在视觉混淆，建议联动气象数据进行告警复核。"],
  }),
  dataListing({
    id: "mock-data-urban-advertising",
    scene: "urban-advertising",
    title: "户外广告与招牌数据集",
    summary: "识别广告牌破损倾斜、广告布脱落、违规横幅和店招掉落风险。",
    taskType: "object-detection",
    assetCount: 500,
    classes: ["广告牌破损", "广告牌倾斜", "广告布脱落", "违规悬挂横幅", "店招破损", "店招掉落风险"],
    source: "暂无公开数据集；可参考 Open Images 的广告牌（Billboard）类别（图像 CC BY 2.0）做基础目标检测。",
    method: "当前标注为演示样例；破损/倾斜/脱落风险类别需自有巡查数据标注。",
    coverage: "楼顶、墙面、门头和道路横幅（演示样例）。",
    limitations: "本卡当前为演示数据，不承诺样本出处；不判断广告内容合规性和结构安全。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "演示样例，正式版本另议",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [{ label: "广告牌倾斜", x: 9, y: 15, width: 27, height: 31 }, { label: "广告布脱落", x: 56, y: 12, width: 33, height: 27 }, { label: "店招破损", x: 39, y: 53, width: 31, height: 25 }],
    coveragePercent: 98.4,
    advisories: ["掉落风险为外观线索，需由专业单位进行结构复核。"],
  }),
  dataListing({
    id: "mock-data-urban-municipal",
    scene: "urban-municipal",
    title: "市政设施损坏数据集",
    summary: "覆盖道路破损、井盖缺失移位、路灯异常、护栏和城市家具损坏。",
    taskType: "object-detection",
    assetCount: 3500,
    classes: ["道路坑槽", "道路破损", "井盖缺失", "井盖移位", "井盖破损", "路灯损坏", "路灯倾斜", "交通护栏损坏", "交通护栏缺失", "座椅破损", "垃圾桶破损"],
    source: "部分可映射公开数据：RDD2022 坑槽子集（约 3,500 实例，CC BY-SA 4.0）；井盖/路灯/城市家具无公开数据集。",
    method: "道路坑槽部分可使用 RDD2022 标注；井盖、路灯等类别当前为演示样例。",
    coverage: "机动车道、非机动车道、人行道；坑槽类为真实公开数据，其余为演示样例。",
    limitations: "仅坑槽类有可靠公开标注，井盖/路灯/护栏为演示数据，不承诺样本出处。",
    license: "CC-BY-SA-4.0",
    commercial: true,
    price: "公开数据集免费获取",
    annotationType: "目标框",
    imageSize: "720p–4K",
    boxes: [{ label: "井盖缺失", x: 24, y: 58, width: 18, height: 16 }, { label: "路灯倾斜", x: 68, y: 7, width: 14, height: 63 }, { label: "道路坑槽", x: 46, y: 71, width: 26, height: 14 }],
    coveragePercent: 98.6,
    advisories: ["井盖和道路破损类别已覆盖多种尺度，仍建议按本地设施规格补充验证。"],
  }),
  dataListing({
    id: "mock-data-urban-water",
    scene: "urban-water",
    title: "河道与水域污染数据集",
    summary: "识别河道漂浮物、水面油污、禁钓禁泳行为及可见污水直排。",
    taskType: "object-detection",
    assetCount: 700,
    classes: ["垃圾漂浮物", "水草漂浮物", "水面油污", "水面彩色污染", "禁钓区垂钓", "禁泳区游泳", "污水直排", "污水偷排"],
    source: "暂无权威公开数据集；学界水面漂浮物数据（RiverTrash/MarineDebris 类）多为论文附帽数据，需向作者申请。",
    method: "当前标注为演示样例；正式版本需采集自有河道巡查画面并标注。",
    coverage: "城市河道、湖泊、闸口和排污口（演示样例）。",
    limitations: "本卡当前为演示数据，不承诺样本出处；水面反光和藻类可能造成误报。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "演示样例，正式版本另议",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [{ label: "垃圾漂浮物", x: 16, y: 55, width: 23, height: 16 }, { label: "水面油污", x: 52, y: 39, width: 32, height: 18 }, { label: "禁钓区垂钓", x: 72, y: 10, width: 15, height: 33 }],
    coveragePercent: 96.7,
    advisories: ["污水直排属于可见线索，正式执法需结合排口检测和取样结果。"],
  }),
  dataListing({
    id: "mock-data-urban-ecology",
    scene: "urban-ecology",
    title: "生态环境问题数据集",
    summary: "覆盖秸秆与垃圾焚烧烟雾、工地扬尘和裸露地块扬尘等环境问题。",
    taskType: "object-detection",
    assetCount: 21527,
    classes: ["秸秆焚烧烟雾", "垃圾焚烧烟雾", "工地扬尘", "裸露地块扬尘"],
    source: "烟雾部分可映射公开数据：D-Fire（21,527 张）与 DFS（9,462 张，含干扰目标类别）；扬尘/裸地无公开数据集。",
    method: "烟雾部分可使用 D-Fire/DFS 标注；工地扬尘、裸地扬尘当前为演示样例。",
    coverage: "城乡结合部、农田、施工区域；烟雾类为真实公开数据，扬尘为演示样例。",
    limitations: "仅烟雾类有可靠公开标注，扬尘类为演示数据；雾霾与云雾易混淆。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "公开数据集免费获取",
    annotationType: "目标框",
    imageSize: "720p–4K",
    boxes: [{ label: "秸秆焚烧烟雾", x: 18, y: 20, width: 30, height: 34 }, { label: "工地扬尘", x: 58, y: 40, width: 30, height: 27 }, { label: "裸露地块扬尘", x: 39, y: 68, width: 28, height: 16 }],
    coveragePercent: 97.2,
    advisories: ["扬尘样本按天气分层，但高湿和逆光条件下仍需人工复核。"],
  }),
  dataListing({
    id: "mock-data-urban-fire",
    scene: "urban-fire",
    title: "火情与安全隐患数据集",
    summary: "识别明火、浓烟、火灾蔓延迹象和易燃物违规堆放等安全隐患。",
    taskType: "object-detection",
    assetCount: 21527,
    classes: ["明火", "浓烟", "火灾蔓延迹象", "易燃物违规堆放"],
    source: "公开数据集 D-Fire（github.com/gaiasd/DFireDataset）：21,527 张真实火烟图像与大量负样本，另有 DFS（9,462 张）可扩充。",
    method: "真实监控与网络图像，明火/烟雾框标注，官方提供划分与基线模型。",
    coverage: "覆盖室内外监控视角、远距离火点与多样烟雾形态。",
    limitations: "原始许可为研究用途授权（引用 Venâncio et al., 2022）；不替代消防报警器。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "公开数据集免费获取",
    annotationType: "目标框",
    imageSize: "720p–4K",
    boxes: [{ label: "明火", x: 48, y: 47, width: 18, height: 27 }, { label: "浓烟", x: 37, y: 10, width: 36, height: 40 }, { label: "易燃物违规堆放", x: 70, y: 64, width: 20, height: 20 }],
    coveragePercent: 98.1,
    advisories: ["火灾蔓延迹象为视觉线索，告警策略需结合消防值守流程。"],
  }),
  dataListing({
    id: "mock-data-urban-crowd",
    scene: "urban-crowd",
    title: "人员聚集与公共安全数据集",
    summary: "识别人员异常聚集、拥堵、突发事件现场和大型活动人流密度异常。",
    taskType: "object-detection",
    assetCount: 4372,
    classes: ["人员异常聚集", "人群拥堵", "突发事件现场", "人流密度异常"],
    source: "公开数据集 JHU-CROWD++（4,372 张人群图像）与 ShanghaiTech A/B（1,914 张、约 33 万人头点标注）。",
    method: "真实监控场景点标注人头密度，支持密度图回归；均为学术研究许可。",
    coverage: "覆盖高/低密度人群、室内外与不同视角。",
    limitations: "人群计数标注而非事件分类，异常聚集事件需自行定义阈值；研究用途许可。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "公开数据集免费获取",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [{ label: "人员异常聚集", x: 30, y: 35, width: 40, height: 35 }, { label: "人群拥堵", x: 58, y: 57, width: 31, height: 27 }, { label: "突发事件现场", x: 9, y: 50, width: 18, height: 22 }],
    coveragePercent: 97.5,
    advisories: ["大型活动阈值应在现场容量和疏散方案基础上配置，不能直接套用样例。"],
  }),
  dataListing({
    id: "mock-data-urban-traffic",
    scene: "urban-traffic",
    title: "交通与停车秩序数据集",
    summary: "覆盖禁停区违法停车、应急车道占用、交通拥堵和占道施工未设警示。",
    taskType: "object-detection",
    assetCount: 100000,
    classes: ["禁停区违法停车", "应急车道占用", "交通拥堵", "占道施工无警示"],
    source: "部分可映射公开数据：BDD100K（10 万驾驶场景，含车辆/行人标注，非商业）；违法停车/占道施工无公开数据集。",
    method: "车辆检测部分可使用 BDD100K/UA-DETRAC 标注；禁停区、应急车道类别需结合电子围栏二次标注。",
    coverage: "路口、主干道、匝道；车辆类为真实公开数据，违停/占道为演示样例。",
    limitations: "BDD100K 为非商业许可；违法停车/应急车道为演示数据，不承诺样本出处。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "公开数据集免费获取",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [{ label: "禁停区违法停车", x: 12, y: 55, width: 30, height: 22 }, { label: "应急车道占用", x: 55, y: 61, width: 28, height: 18 }, { label: "占道施工无警示", x: 65, y: 18, width: 24, height: 28 }],
    coveragePercent: 98.4,
    advisories: ["禁停区和应急车道标签需与道路电子地图及现场标线保持同步。"],
  }),
  dataListing({
    id: "mock-data-urban-greening",
    scene: "urban-greening",
    title: "园林绿化问题数据集",
    summary: "识别毁绿种菜、树木倒伏折断、绿化带垃圾和绿地黄土裸露。",
    taskType: "object-detection",
    assetCount: 500,
    classes: ["毁绿种菜", "树木倒伏", "树木折断", "绿化带垃圾堆积", "绿地黄土裸露"],
    source: "暂无公开数据集；可参考 Roboflow Universe 社区树木/绿化数据，许可需逐个核验。",
    method: "当前标注为演示样例；正式版本需采集自有绿化巡查画面并标注。",
    coverage: "行道树、花坛、草坪和社区绿地（演示样例）。",
    limitations: "本卡当前为演示数据，不承诺样本出处；季节性裸土易与养护作业混淆。",
    license: "CUSTOM-RESEARCH",
    commercial: false,
    price: "演示样例，正式版本另议",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [{ label: "毁绿种菜", x: 14, y: 54, width: 28, height: 22 }, { label: "树木倒伏", x: 51, y: 40, width: 35, height: 19 }, { label: "绿地黄土裸露", x: 60, y: 68, width: 27, height: 15 }],
    coveragePercent: 98,
    advisories: ["季节性养护区域已做对照标注，仍建议与园林作业计划联动。"],
  }),
];

const previewFallbacks: CatalogPreview[] = MOCK_ALGORITHM_LISTINGS.map((item) => item.preview);

export function decorateAlgorithmListing(listing: MarketplaceListing, index = 0): AlgorithmCatalogItem {
  const preview = previewFallbacks[index % previewFallbacks.length];
  return {
    ...listing,
    is_mock: false,
    preview,
    metrics: listing.metrics?.length
      ? listing.metrics
      : [
        { label: "调用状态", value: "可用" },
        { label: "模型版本", value: `v${listing.model_version_number}` },
        { label: "月度额度", value: listing.monthly_quota_units.toLocaleString("zh-CN") },
      ],
    classes: listing.classes ?? [],
    model_architecture: listing.model_architecture ?? listing.model_name,
    input_size: listing.input_size ?? "按接口说明",
    latency_p95: listing.latency_p95 ?? "待供应商公布",
    evaluation_basis: "以供应商发布的验收材料为准",
    updated_label: listing.published_at ? listing.published_at.slice(0, 10) : "近期发布",
  };
}

export function decorateDataListing(listing: DataMarketListing, index = 0): DataCatalogItem {
  const preview = previewFallbacks[index % previewFallbacks.length];
  return {
    ...listing,
    is_mock: false,
    preview,
    scene_category: dataSceneCategories[preview.scene],
    price_label: "联系供应方",
    annotation_type: listing.task_type === "segmentation" ? "多边形分割" : "目标框",
    image_size_summary: listing.quality_report?.image_dimensions.max_width
      ? `最长边 ${listing.quality_report.image_dimensions.max_width}px`
      : "尺寸待确认",
    updated_label: listing.published_at.slice(0, 10),
  };
}

export function mergeAlgorithmListings(listings: MarketplaceListing[], includeMocks = false): AlgorithmCatalogItem[] {
  const real = listings.map(decorateAlgorithmListing);
  return includeMocks
    ? [...real, ...MOCK_ALGORITHM_LISTINGS.filter((mock) => !real.some((item) => item.title === mock.title))]
    : real;
}

export function mergeDataListings(listings: DataMarketListing[], includeMocks = false): DataCatalogItem[] {
  const real = listings.map(decorateDataListing);
  return includeMocks
    ? [...real, ...MOCK_DATA_LISTINGS.filter((mock) => !real.some((item) => item.title === mock.title))]
    : real;
}

export function findMockAlgorithm(id: string): AlgorithmCatalogItem | null {
  return MOCK_ALGORITHM_LISTINGS.find((item) => item.id === id) ?? null;
}

export function findMockData(id: string): DataCatalogItem | null {
  return MOCK_DATA_LISTINGS.find((item) => item.id === id) ?? null;
}
